//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWO
    {
        public long ID { get; set; }
        public int CONTRACTID { get; set; }
        public int IPOID { get; set; }
        public string CUTOO { get; set; }
        public string CUOBJ { get; set; }
        public string OBJSNAME { get; set; }
        public string CHASSINO { get; set; }
        public string UPPLAGG { get; set; }
        public string LOPNR { get; set; }
        public string ORDERREF { get; set; }
        public string POPID { get; set; }
        public string PRODUCT_INDIVIDUAL { get; set; }
        public string PLSTART { get; set; }
        public string CIIDNO { get; set; }
        public Nullable<int> DCIREF { get; set; }
        public string TYPEPLATE { get; set; }
        public Nullable<int> TYPEDES1 { get; set; }
        public Nullable<int> TYPEDES2 { get; set; }
        public Nullable<int> TYPEDES3 { get; set; }
        public Nullable<int> TYPEDES4 { get; set; }
        public Nullable<int> TYPEDES5 { get; set; }
        public Nullable<int> TYPEDES6 { get; set; }
        public Nullable<int> TYPEDES7 { get; set; }
        public Nullable<int> TYPEDES8 { get; set; }
        public Nullable<int> TYPEDES9 { get; set; }
        public Nullable<int> TYPEDES10 { get; set; }
        public string PARTPER { get; set; }
        public string PAOBJ { get; set; }
        public string VINCODE { get; set; }
        public Nullable<System.DateTime> DATE_INSERTED { get; set; }
    }
}
