//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWO_TASKROW
    {
        public long ID { get; set; }
        public int CONTRACTID { get; set; }
        public int IPOID { get; set; }
        public string WPLOBJ { get; set; }
        public string TASKOBJ { get; set; }
        public string TOO { get; set; }
        public string OBJ { get; set; }
        public string SNAME { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string CCPOSNO { get; set; }
        public string CIIDNO { get; set; }
        public string CONID { get; set; }
        public Nullable<int> POSNO { get; set; }
        public string LNAME { get; set; }
        public Nullable<int> LINENUM { get; set; }
    }
}
