//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTSEntities : DbContext
    {
        public LTSEntities()
            : base("name=LTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EWO> EWO { get; set; }
        public virtual DbSet<EWO_TASKROW> EWO_TASKROW { get; set; }
        public virtual DbSet<TB_FUNCTION> TB_FUNCTION { get; set; }
        public virtual DbSet<TB_STATION> TB_STATION { get; set; }
        public virtual DbSet<TB_WORKPLACE> TB_WORKPLACE { get; set; }
        public virtual DbSet<DRUN> DRUN { get; set; }
    }
}
