//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_STATION()
        {
            this.TB_WORKPLACE = new HashSet<TB_WORKPLACE>();
        }
    
        public int ID { get; set; }
        public int ID_FUNCTION { get; set; }
        public int POSITION { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual TB_FUNCTION TB_FUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WORKPLACE> TB_WORKPLACE { get; set; }
    }
}
