//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtsApi.MixService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MixService.IMixService")]
    public interface IMixService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetData", ReplyAction="http://tempuri.org/IMixService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetData", ReplyAction="http://tempuri.org/IMixService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetListByContract", ReplyAction="http://tempuri.org/IMixService/GetListByContractResponse")]
        string GetListByContract(long contractId, int qty, string requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetListByContract", ReplyAction="http://tempuri.org/IMixService/GetListByContractResponse")]
        System.Threading.Tasks.Task<string> GetListByContractAsync(long contractId, int qty, string requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetListPlannedMix", ReplyAction="http://tempuri.org/IMixService/GetListPlannedMixResponse")]
        string GetListPlannedMix(long contractId, System.DateTime dateMix, int sequenceIni, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMixService/GetListPlannedMix", ReplyAction="http://tempuri.org/IMixService/GetListPlannedMixResponse")]
        System.Threading.Tasks.Task<string> GetListPlannedMixAsync(long contractId, System.DateTime dateMix, int sequenceIni, int qty);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMixServiceChannel : LtsApi.MixService.IMixService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MixServiceClient : System.ServiceModel.ClientBase<LtsApi.MixService.IMixService>, LtsApi.MixService.IMixService {
        
        public MixServiceClient() {
        }
        
        public MixServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MixServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MixServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetListByContract(long contractId, int qty, string requester) {
            return base.Channel.GetListByContract(contractId, qty, requester);
        }
        
        public System.Threading.Tasks.Task<string> GetListByContractAsync(long contractId, int qty, string requester) {
            return base.Channel.GetListByContractAsync(contractId, qty, requester);
        }
        
        public string GetListPlannedMix(long contractId, System.DateTime dateMix, int sequenceIni, int qty) {
            return base.Channel.GetListPlannedMix(contractId, dateMix, sequenceIni, qty);
        }
        
        public System.Threading.Tasks.Task<string> GetListPlannedMixAsync(long contractId, System.DateTime dateMix, int sequenceIni, int qty) {
            return base.Channel.GetListPlannedMixAsync(contractId, dateMix, sequenceIni, qty);
        }
    }
}
